allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': false
  '@scarf/scarf': false
  bcrypt: true
  esbuild: true
  msgpackr-extract: set this to true or false
  prisma: false
  unrs-resolver: false
  workerd: set this to true or false
